version = 1
SPDX-PackageName = "vendor-win-iconv"
SPDX-PackageSupplier = "Grigore Stefan <g_stefan@yahoo.com>"
SPDX-PackageDownloadLocation = "https://github.com/g-stefan/vendor-win-iconv"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ".github/CODE_OF_CONDUCT.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Coraline Ada Ehmke <https://where.coraline.codes/>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ".vscode/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "mkdocs.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "build/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "build.cmd"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "build.sh"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["archive/**", "source/**", "output/**", "temp/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = ""
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = "test/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ["version.ini", "version.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021-2026 Grigore Stefan <g_stefan@yahoo.com>"
SPDX-License-Identifier = "Unlicense"
